spring:
  application:
    name: system-eureka-service
server:
  port: 1001
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
    basedir:
      /usr/local/jxmcloud/eureka
    accesslog:
      enabled: true
logging:
  config: classpath:logback-prod.xml


eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    hostname: 172.18.166.161
  server:
    enable-self-preservation: false #Eureka自我保护机制以及心跳周期长会遇到 Eureka不剔除已关停的节点的问题，默认打开状态。建议生产环境打开此配置
    eviction-interval-timer-in-ms: 10000 #清理间隔（单位毫秒，默认是60*1000）
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@172.18.166.161:1001/eureka/