server:
  port: 3001

spring:
  application:
    name: whstone-system-zuul
  swagger:
    enable: true

#--------------------Zuul-----------------------
zuul:
  routes:
    whstone-user:
      path: /user-server/**
      serviceId: whstone-system-user
      stripPrefix: true
      sensitiveHeaders:
    whstone-monitor:
      path: /monitor-server/**
      serviceId: whstone-monitor-focus
      stripPrefix: true
      sensitiveHeaders:
    whstone-inspection:
      path: /inspection-server/**
      serviceId: whstone-inspection-focus
      stripPrefix: true
      sensitiveHeaders:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3500