server:
  port: 4001

spring:
  application:
    name: whstone-redis-server
  swagger:
    enable: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 20000
    pool:
      max-wait: 1
      max-idle: 8
      min-idle: 0
      max-active: 8

logging:
  config: classpath:logback-spring.xml
  file: log/system_user.log
  level:
    #设置包的日志级别
    com.example.monitor_server: debug
