server:
  port: 2001

spring:
  application:
    name: whstone-system-user
  swagger:
    enable: true

mybatis:
  type-aliases-package:  com.whstone.user.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/**.xml
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count:countSql
druid:
  url: jdbc:mysql://127.0.0.1:3306/ecloud_user?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
  driver-class: com.mysql.jdbc.Driver
  username: root
  password: root
  initialSize: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true
logging:
  config: classpath:logback-spring.xml
  file: log/system_user.log
  level:
    #设置包的日志级别
    com.example.monitor_server: debug

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true

# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3500
